# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPageData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to=b'')),
                ('time_created', models.DateTimeField(auto_now=True)),
                ('time_updated', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
