# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-26 11:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userpagedata',
            table='user_page_data',
        ),
    ]
