# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0004_auto_20160229_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiledata',
            name='age',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='userprofiledata',
            name='status',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
