# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 14:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userpage', '0006_auto_20160229_1648'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofiledata',
            name='subscriptions',
        ),
        migrations.AddField(
            model_name='userprofiledata',
            name='subscriptions',
            field=models.ManyToManyField(related_name='followed', to=settings.AUTH_USER_MODEL),
        ),
    ]
