# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 16:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0007_auto_20160229_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofiledata',
            name='subscriptions',
            field=models.ManyToManyField(blank=True, related_name='followed', to=settings.AUTH_USER_MODEL),
        ),
    ]
