# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-29 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpage', '0008_auto_20160229_1916'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpagedata',
            name='image',
            field=models.ImageField(null=True, upload_to=b''),
        ),
    ]
