# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('untitled', '0003_user_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='J',
        ),
        migrations.DeleteModel(
            name='K',
        ),
    ]
