# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 17:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('untitled', '0004_auto_20160219_2038'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='UserPage',
        ),
    ]
