# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 17:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('untitled', '0005_auto_20160219_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpage',
            name='timeCreated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 2, 19, 17, 50, 9, 806000, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpage',
            name='timeUpdated',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 2, 19, 17, 50, 32, 895000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
